### ISSUE TITLE
A gap is created when having padding

### ISSUE THREAD

**Issue by jenstornell** [cferdinandi/right-height#26]
I get a big gap when using this. The element have padding. It's not compensating for it.

![jamfor smslan och blancolan lanera](https://cloud.githubusercontent.com/assets/927011/9955908/b488ba2e-5df4-11e5-86eb-cf2bbbe67f88.png)

Else I use matchheight, but want to use something that does not require jQuery. This would be a nice fit, if it would work like expected.

**Update**

I workaround is to add a div clean from styling inside the padding element, like this:

    <div data-right-height-content>

**Comment by cferdinandi** [comment]
Sounds like you got things working

**Comment by jenstornell** [comment]
You really are fast on the issue close-button. ;)

This time I agree with you. Adding an extra div is ok and trying to compensate it with js would probably just bloat the it anyway.
