### ISSUE TITLE
Allow for multiple selectorContent variables

### ISSUE THREAD

**Issue by eliwilliamson** [cferdinandi/right-height#29]
Would be nice to add 2 different data attributes so i can have multiple elements adjusting their height at the same time. For example, i wanted one set of divs to match the height of the tallest div and another, seperate set of divs set to match the height of that different set. Does that make sense? Seems like right now you can only adjust the height of one set at a time on the page.

**Comment by cferdinandi** [comment]
You can't nest areas, but you can have more than one content area. ie. this is already supported.

**Comment by eliwilliamson** [comment]
Is there documentation or an example of this you can point me towards?

-Eli

**Comment by cferdinandi** [comment]
@eliwilliamson Sorry for being so brief in my original response. Allow me to elaborate and providing some sample code.

When you run `rightHeight.init()`, it makes a list of every element with the `[data-right-height]` data attribute. For each of these elements, it locates all of the elements inside it with the `[data-right-height-content]` attribute, finds the tallest one, and sets the height of all of them to the height of this tallest element.

It does this for every `[data-right-height]` element individually, so the height of content inside one doesn't affect the height of the content in another.

**You can just do this:**

```html
<div class="row" data-right-height>
	<div class="grid-third">
		<div class="hero" data-right-height-content>
			<h2>Content 1</h2>
			<p>Some text.</p>
		</div>
	</div>
	<div class="grid-third">
		<div class="hero" data-right-height-content>
			<h2>Content 2</h2>
			<p>Some text.</p>
		</div>
	</div>
	<div class="grid-third">
		<div class="hero" data-right-height-content>
			<h2>Content 3</h2>
			<p>Some text.</p>
		</div>
	</div>
</div>

<div class="row" data-right-height>
	<div class="grid-third">
		<div class="hero" data-right-height-content>
			<h2>More Content 1</h2>
			<p>Some other text.</p>
		</div>
	</div>
	<div class="grid-third">
		<div class="hero" data-right-height-content>
			<h2>More Content 2</h2>
			<p>Some other text.</p>
		</div>
	</div>
	<div class="grid-third">
		<div class="hero" data-right-height-content>
			<h2>More Content 3</h2>
			<p>Some other text.</p>
		</div>
	</div>
</div>
```

However, you cannot nest one `[data-right-height]` element inside another `[data-right-height]` element. 

**This WON'T work:**

```html
<div class="row" data-right-height>
	<div class="grid-third">
		<div class="hero" data-right-height-content>
			<h2>Content 1</h2>
			<p>Some text.</p>
		</div>
	</div>
	<div class="grid-third">
		<div class="hero" data-right-height-content>
			<h2>Content 2</h2>
			<p>Some text.</p>
		</div>
	</div>
	<div class="grid-third">
		<div class="hero" data-right-height-content>
			<h2>Content 3</h2>
			<p>Some text.</p>

			<div class="row" data-right-height>
				<div class="grid-third">
					<div class="hero" data-right-height-content>
						<h2>More Content 1</h2>
						<p>Some other text.</p>
					</div>
				</div>
				<div class="grid-third">
					<div class="hero" data-right-height-content>
						<h2>More Content 2</h2>
						<p>Some other text.</p>
					</div>
				</div>
				<div class="grid-third">
					<div class="hero" data-right-height-content>
						<h2>More Content 3</h2>
						<p>Some other text.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
```

Does that help clear things up at all?

**Comment by cferdinandi** [comment]
Also, I used the default selectors in these examples, but if you switched them out for classes or whatever, the same principle applies.

**Comment by eliwilliamson** [comment]
Thank you, that does help however what I'm asking is lets say you have something like:

<div data-right-height>

<div data-right-height-content1>...</div>
<div data-right-height-content1>...</div><div data-right-height-content2>...</div>
<div data-right-height-content2>...</div>

</div>

Two different height sets within one wrapper.

I don't think this is currently possible right now, am I wrong?

Thank you!

-Eli

**Comment by cferdinandi** [comment]
Ohhh... definitely not possible, *unless* the `content-2` stuff is just stuff you don't want adjusted at all. What you're describing sounds like a candidate for flexbox, though browser support for that is spotty at best.
