### ISSUE TITLE
Match height per row (not all items)

### ISSUE THREAD

**Issue by jackbarham** [cferdinandi/right-height#35]
Is it possible to match the height per row?

I have several rows (responsive) and the height matched is the largest of all items, but these are spread over several rows so they all have the same height. Is it possible to match them based on the current row they are in?

**Comment by cferdinandi** [comment]
I normally suggest that each row of content has it's own `data-right-height` container, for example:

```html
<div data-right-height>
    <div data-right-height-content>
        1
    </div>
    <div data-right-height-content>
        2
    </div>
    <div data-right-height-content>
        3
    </div>
</div>

<div data-right-height>
    <div data-right-height-content>
        4
    </div>
    <div data-right-height-content>
        5
    </div>
    <div data-right-height-content>
        6
    </div>
</div>
```

However, I'm assuming that in your case, depending on the size of the viewport the content wraps differently? For example, single column on small viewports, two column on mid-sized viewports, three column on larger viewports, and so on.

That use case has been on my radar for a while, and supporting it is something I *could* bake in to this plugin, but honestly just haven't had the time.

I would need to programmatically group content into rows by measuring the distance of each `data-right-height-content` from the top of the page. Those with the same distance are part of a row.

Anyways, I'm going to flag this as a feature request, but can't commit on a timeline for implementing.

**Comment by cferdinandi** [comment]
I've decided to deprecate this plugin, as this is now better handled with [Flexbox](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox) and [CSS Grid Layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout).
